version: 2
updates:
  - package-ecosystem: github-actions
    directory: ""
    target-branch: main
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: ""
    target-branch: main
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: ""
    target-branch: main
    schedule:
      interval: daily
